### ISSUE TITLE
fix: 手贱在“人物”里加了自己好友，啥也点不动了。

### ISSUE THREAD

**Issue by carasue** [706YouthSpace/agora-wxa#4]
杀了微信进程后再打开恢复,好友列表里出现了自己。 
“人物“里还可以拉黑自己

**Comment by nomagick** [comment]
HMM。。。不知道为啥会死。。。

我自己好像也加了我自己为好友的，理论上可以，我没拦着，就这样了

**Comment by nomagick** [comment]
fixed by e21fd07301eae828ab9eea499c92f112e89b14f3
