### ISSUE TITLE
fix: 修改个人资料的地方 可见性应当是保存过的值，不应当都是“公开”

### ISSUE THREAD

**Issue by carasue** [706YouthSpace/agora-wxa#5]

**Comment by nomagick** [comment]
指的是后三项大的textarea？ 这部分是杨树专门定的，必须公开的部分

**Comment by carasue** [comment]
> 指的是后三项大的textarea？ 这部分是杨树专门定的，必须公开的部分

不是，正确的思路应该是，比如我这次设置我的职务为私密；
下次我再点进来编辑，目的是想把我的专业设置为私密。  
我看到的职务默认值应该是私密，而不是公开。
要不然我要达到我的目的（只是把专业修改为私密，其他设置不变），就必须再手动把职务也设置为私密，不然我的职务又公开了

**Comment by nomagick** [comment]
蛤，现在是这样的吗？那有问题啊，我还以为这个之前已经实现好了

**Comment by carasue** [comment]
> 蛤，现在是这样的吗？那有问题啊，我还以为这个之前已经实现好了

是的，那就是bug，可以复现
